APP/urls.py
from django.urls import path
from . import views
from .views import BonzaiListView

urlpatterns = [
    path('', views.BonzaiList, name="accueil"),
    path('bonzai/<int:pk>', views.BonzaiDetailView.as_view(), name = 'detail_bonzai'),
    path('bonzai_cat/<str:typarbre>', views.BonzaiListView.as_view(), name= 'bonzai_par_type'),
    path('bonzai/create', views.BonzaiCreate, name='bonzai_create'),
    path('bonzai/update/<int:pk>', views.bonzai_update, name='bonzai_update'),
    path('bonzai/delete/<int:pk>', views.bonzai_delete, name='bonzai_delete'),
    ]

PROJECT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('APP.urls')),
    path('', include('inscription.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

APP/models.py
from django.db import models


# Create your models here.


class TypeFeuille(models.Model):
    name = models.CharField(max_length=15, default="Indefini")
        
    def __str__(self):
        return self.name

class Bonzai(models.Model):
    nom = models.CharField(max_length=50)
    age = models.PositiveSmallIntegerField()
    taille = models.DecimalField(max_digits=3, decimal_places=2)
    pays_origine = models.CharField(max_length=15, blank=False, null=False)
     
    
    FEUILLU_CADUQUE = 'FEUIL-CADU'
    FEUILLU_PERSISTANT = 'FEUIL-PERS'
    CONIFERE_PERSISTANT = 'CONIF-PERS'
    TYPE_ARBRE_CHOICES =[
        (FEUILLU_CADUQUE, 'FEUILLU CADUQUE'),
        (FEUILLU_PERSISTANT, 'FEUILLU PERSISTANT'),
        (CONIFERE_PERSISTANT, 'CONIFERE PERSISTANT')
        ]
        
    type_arbre = models.CharField(max_length=10,
        choices = TYPE_ARBRE_CHOICES,
        default= FEUILLU_CADUQUE,
        verbose_name ="Type d'arbre"
    ) 

    type_feuille = models.ForeignKey(TypeFeuille, on_delete=models.CASCADE)
    provenance = models.CharField(max_length=20)
    img_arbre = models.ImageField(null = True, blank = True, upload_to='logo')

    def __str__(self): 
        return '{} {}'.format(self.nom, self.type_arbre)
    
    @classmethod
    def BonzaiSearchList(cls):
        l = cls.TYPE_ARBRE_CHOICES
        ltype =[]
        typedict={}    
        for t in l:
            typedict[t[0]] = t[1]
            ltype.append(typedict)
            typedict={}
        
        extra = {'ltreetype': ltype}
        return extra

APP/templates/bonzai/bonzai.html
{% extends 'base.html' %}

{% block title %}
    Les bonzaïs d'Armel
{% endblock title %}

{% block title_header %}
    Les bonzaïs d'Armel
{% endblock title_header %}

{% block container_1 %}
<h4 class="titre-section"> Première présentation </h4>
    <div class="card-columns">
        {% for b in bonzai_list %}
            <div class="card">
                <img class="card-img-top" src="{{ b.img_arbre.url }}" alt="{{ b.nom }}" >
                <div class="card-body ">
                    <h4 class="card-title text-center">{{ b.nom }} </h4>
                    <p class="card-text text-center">{{ b.age}} ans {{ b.taille }}m </p>
                    <div class="text-center">
                    <a href="{% url 'detail_bonzai' b.id %}" class="btn btn-success">Voir la description</a>
                    </div>
                </div>
            </div>    
        {% endfor %}
    </div>
{% endblock container_1 %}

{% block container_2 %}
<h4 class="titre-section"> Deuxième présentation </h4>
    <div class="card-deck">
        {% for b in bonzai_list %}
            <div class="card" id="iemepres">
                <img class="card-img-top" src="{{ b.img_arbre.url }}" alt="{{ b.nom }} ">
                <div class="card-body">
                    <h4 class="card-title text-center">{{ b.nom }} </h4>
                    <p class="card-text text-center">{{ b.age}} ans {{ b.taille }}m </p>
                    <div class="text-center">
                    <a href="#" class="btn btn-success">Voir la description</a>
                    </div>
                </div>
            </div>    
        {% endfor %}
    </div>
{% endblock container_2 %}

APP/templates/bonzai/bonzai_delete.html
{% extends 'base.html' %}
{% block title %}
Suppression Bonzaï
{% endblock %}
{% block title_header %}
Suppression d'un bonzaï
{% endblock title_header %}
{% block container_1 %}
<div class="container text-center" id= "delete_group">
  <form class="form-group" method="post">
    {% csrf_token %}
    <p>Etes-vous sur de vouloir supprimer {{ bonzai.nom }}?</p>
    <input type="submit" name="" value="submit" class="btn btn-danger">
  </form>
</div>
{% endblock %}

APP/templates/bonzai/bonzai_form.html
{% extends 'base.html' %}
{% block title %}
Création d'un bonzaï
{% endblock %}
{% block title_header %}
Création d'un bonzaï
{% endblock title_header %}
{% block container_1 %}
<div class="container text-center" id="insert_group">
  <form class="form-group" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="" value="submit" class="btn btn-success">
  </form>
</div>
{% endblock container_1 %}

APP/templates/bonzai/detail_bonzai.html
{% extends 'base.html' %}

{% block title %}
    Les bonzais d'Armel  {{ object.nom }}
{% endblock title %}

{% block title_header %}
    {{ object.nom }} {{ object.type_arbre }}
{% endblock title_header %}

{% block container_1 %}
    <div class="detail-b">
        <h4 class="title-detail">{{ object.nom }}</h4>
        <img src="{{ object.img_arbre.url }}" alt="{{ object.nom }}" class="pictdetail"></img>
        <h5> Description:</h5>
        <p> {{object.nom}} est à arbre à feuilles {{ object.type_feuille.name }}</p>
        <a href ="{% url 'bonzai_update' object.id%} "><i class="fas fa-user-edit"></i></a>
        <a href ="{% url "bonzai_delete" object.id%} "><i class="far fa-trash-alt"></i></a>
        <p class="text-center">{% lorem 4 b random %}</p>
    </div>
{% endblock container_1 %}